# Generated by Django 5.1 on 2024-08-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecommendation',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
